// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jipldlklzobiytkvxokf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcGxkbGtsem9iaXl0a3Z4b2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NDgzNjksImV4cCI6MjA4MzAyNDM2OX0.lz8n02a36iOwRHsfPTwMktpYYXJrKCoSSW9gezUan_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});